version: '3.1'

services:
  podkashde.app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: podkashde
    ports:
      - 8083:80
    env_file: .env
    volumes:
      - ./public-docker:/var/www/public/s
    environment:
      - VIRTUAL_HOST=podk.calvarychapel.de
      - LETSENCRYPT_HOST=podk.calvarychapel.de