version: '3.1'

services:
  podkashde.app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: podkashde
    ports:
      - 8083:3000
    env_file: .env
    volumes:
      - ./.output/public:/podkashde/public
    environment:
      - VIRTUAL_HOST=podk.calvarychapel.de
      - LETSENCRYPT_HOST=podk.calvarychapel.de