FROM node:16
LABEL authors="Alex Roehm"

RUN apt-get update && apt-get install -y \
    curl dumb-init logrotate nginx\
    && rm -rf /var/lib/apt/lists/*

COPY ./docker/nginx/startup-dev.sh /startup.sh
RUN chmod u+x /startup.sh

COPY ./docker/nginx/default /etc/nginx/sites-available/default
COPY ./docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY ./docker/nginx/logrotate /etc/logrotate/nginx
RUN chmod go-w /etc/logrotate/nginx

RUN chown -R node:node /etc/nginx /var/log/nginx /var/lib/nginx 
RUN chmod a+w /run

USER node
WORKDIR /var/www
RUN yarn

EXPOSE 80
EXPOSE 3000
EXPOSE 24678

ENTRYPOINT ["/usr/bin/dumb-init", "--"]
CMD [ "/startup.sh" ]