version: '3.1'

services:
  podkashde.app:
    image: ghcr.io/ccfreiburg/podkashde:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    container_name: podkashde.app
    ports:
      - 3333:3000
    env_file: .env
    volumes:
      - ../public/s:/var/www/public/s
