export const DATA_PATH ="public";
export const ARCHIV_PATH ="archiv";
export const PUBLIC_RESOURCES = 'public';
export const FEED_SLUG = '/s/feed/';
export const SERVER_IMG_PATH = '/s/covers/';
export const SERVER_MP3_PATH = '/s/audio/';
export const SERVER_POSTIMG_PATH = '/s/posts/';
export const SERIES_IMG_PATH = 'series';
export const REQUIRED_IMG_WIDTH = 1400;
export const REQUIRED_IMG_HEIGHT = 1400;
export const UPLOAD_AP = 'upload';
export const UPLOAD_TEMP_PATH = 'public/s/upload/';
export const FETCHLOCAL_AP = 'fetchfile';
export const FROMARCHIVE_AP = 'fromarchive';
export const SERIES_AP = 'series';
export const SERIE_AP = 'serie';
export const PODCAST_AP = 'podcast';
export const PODCASTS_AP = 'podcasts';
export const EPISODES_AP = 'episodes';
export const EPISODE_AP = 'episode';
export const EPISODEWP_AP = 'episodewp';
export const EPISODEMOVE_AP = 'episodemove';
export const COUNT_AP = 'count';
export const ENUMERATIONS_AP = 'enums';
export const GENERATE_RSS_AP = 'generaterss';
export const WP_API_SLUG = 'wp-json/wp/v2/';
export const WP_PER_PAGE = '?per_page=100';
export const WP_MIN_PER_PAGE = '?per_page=1';
export const WP_HEADER_TOTAL = 'x-wp-total';
export const ROUTE_NEWPODCAST = 'newpodcast';
export const LOGIN_AP = 'auth/login';
export const LOGOUT_AP = 'auth/logout';
export const REFRESH_AP = 'auth/refresh';
export const AUTHUSER_AP = 'auth/user';
export const USERTOKEN_AP = 'auth/usertoken?username=%%&type=';
export const FILES_AP = 'files?path=';
export const INVITE_TOKEN = 'invitation';
export const INVITE_TIME = '2d';
export const PWRESET_TIME = '1d';
export const SETPASS_LINK = '/admin/setpassword?token=';
export const CHECK_TOKEN_AP = 'auth/checktoken?token=';
export const PASSWORD_AP = 'auth/password'
export const NUM_PAGINATION_LINKS = 7
export const NUM_ITEMS_PER_PAGE = 6
export const TOKEN_REFRESH_TIME = 60000