name: End-to-end tests
on: 
    push: 
        branches: [ "refactor/separate-backend" ]
    workflow_dispatch:
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run backend
        uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: |
          cd backend &&
          yarn &&
          yarn start &
      - name: Run E2E tests
        uses: cypress-io/github-action@v5
        with:
          start: yarn preview
          wait-on: http://localhost:3000